apiVersion: v1
data:
  postgresql.conf: |
    # PostgreSQL configuration file

    #------------------------------------------------------------------------------
    # CONNECTIONS AND AUTHENTICATION
    #------------------------------------------------------------------------------

    # Listen on all interfaces
    listen_addresses = '*'

    # Allow connections from any IP address
    # Replace <ip_address_range> with the IP address range you want to allow connections from
    # For example, '192.168.1.0/24' to allow connections from the 192.168.1.x subnet
    # Or '0.0.0.0/0' to allow connections from any IP address (not recommended)
    #host    all             all             <ip_address_range>        md5
    host    all             all             all                     md5

    # Use md5 password authentication
    password_encryption = md5

    # Set the maximum number of connections
    max_connections = 100

    #------------------------------------------------------------------------------
    # RESOURCE USAGE (except WAL)
    #------------------------------------------------------------------------------

    # Set the shared buffer size (in MB)
    shared_buffers = 128MB

    # Set the work memory size (in MB) for each query
    work_mem = 4MB

    # Set the maintenance work memory size (in MB)
    maintenance_work_mem = 64MB

    #------------------------------------------------------------------------------
    # WRITE AHEAD LOG
    #------------------------------------------------------------------------------

    # Set the WAL level to minimal
    wal_level = minimal

    # Set the minimum number of WAL segments to keep before recycling
    min_wal_segments = 4

    # Set the maximum number of WAL segments to keep before recycling
    max_wal_segments = 8

    # Set the size of each WAL segment (in MB)
    wal_segment_size = 16MB

    # Set the location of the WAL files
    # Replace <path_to_wal_files> with the actual path to the directory where you want to store the WAL files
    # For example, '/var/lib/postgresql/data/pg_wal' if you want to store them in the 'pg_wal' subdirectory of the data directory
    # Or '/mnt/pg_wal' if you want to store them in a separate directory mounted as a volume
    # Make sure that the directory exists and is writable by the PostgreSQL user
    wal_keep_segments = 8
    wal_keep_size = 1GB
    wal_level = replica
    archive_mode = on
    archive_command = 'cp %p /var/lib/postgresql/data/pg_wal/%f'

    #------------------------------------------------------------------------------
    # QUERY TUNING
    #------------------------------------------------------------------------------

    # Enable parallel query execution
    max_parallel_workers_per_gather = 2
    max_parallel_maintenance_workers = 1

    # Enable JIT compilation of queries
    jit = on

    # Set the default statistics target
    default_statistics_target = 100

    # Set the minimum number of rows to sample for statistics
    # This should be set to a value that is representative of the data distribution
    # If your tables have a large number of rows, you can increase this value to improve query planning
    min_wal_size = 64MB
    max_wal_size = 1GB
    max_worker_processes = 4
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgres-config
