apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
      # nodeSelector:
      #   ingress-ready: true
      #   kubernetes.io/os: linux
    spec:
      nodeSelector:  
        ingress-ready: "true"
        kubernetes.io/os: linux
      containers:
      - name: postgres-db
        image: postgres:15.1-alpine
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-password
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        
        # - name: postgres-config
        #   mountPath: /etc/postgresql/postgresql.conf
        #   subPath: postgresql.conf
      volumes:
      - name: postgres-data
        # emptyDir: {}      //?Gives Epheremeral storage
        hostPath:
          path: /root/work/K8sRegularTrainingTasks/Task2_K8s_management/kubernetes/data
      - name: postgres-config
        configMap:
          name: postgres-config
      # resources:
      #   limits: 
      #     memory: 20Mi
      #   requests:
      #     memory: 10Mi
